name: Help Wanted
description: Ask for help from the developer and the community
title: "[Help Wanted]: "
labels: ["help wanted"]
body:
  - type: checkboxes
    id: before-reporting
    attributes:
      label: Before Reporting
      description: Before asking for help, we suggestion that you first refer to the [FAQ](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions) to check if it may address your issue. And search for existing issues to avoid duplication.
      options:
        - label: I have checked FAQ, and there is no solution to my issue
          required: true
        - label: I have searched the existing issues, and there is no existing issue for my issue
          required: true
  - type: textarea
    id: what-help
    attributes:
      label: Describe your issue
      description: Please describe the help you want.
      placeholder: My issue is...
      value: "I want help!"
    validations:
      required: true
